"""Core domain models shared across all modules."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum


class Direction(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderStatus(str, Enum):
    PENDING = "pending"
    FILLED = "filled"
    PARTIAL = "partial"
    CANCELLED = "cancelled"


class PriceType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"


@dataclass(frozen=True)
class StockInfo:
    """Basic stock information."""

    code: str  # e.g. "000001"
    name: str
    exchange: str  # "SZ" or "SH"
    list_date: date
    industry: str = ""

    @property
    def symbol(self) -> str:
        """Full symbol like '000001.SZ'."""
        return f"{self.code}.{self.exchange}"


@dataclass(frozen=True)
class BarData:
    """Single OHLCV bar."""

    code: str
    date: date
    open: float
    high: float
    low: float
    close: float
    volume: float
    amount: float
    turnover: float = 0.0  # 换手率


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    stock_code: str
    direction: Direction
    strength: float  # 0.0 to 1.0
    reason: str
    timestamp: datetime = field(default_factory=datetime.now)
    entry_strategy: str = ""
    """For BUY signals from the ensemble/LLM path: the single strategy that
    contributed most to this pick (argmax of weight×strength). Persisted onto
    the position so an exit can replay *that* strategy's logic. Empty when the
    buy wasn't strategy-led (pure factor/sentiment) or in single-strategy mode
    (the position's strategy is unambiguous anyway)."""


@dataclass
class Order:
    """Trade order."""

    stock_code: str
    direction: Direction
    quantity: int  # Must be multiple of 100
    price_type: PriceType = PriceType.MARKET
    limit_price: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    strategy_name: str = ""
    filled_price: float = 0.0
    filled_quantity: int = 0
    created_at: datetime = field(default_factory=datetime.now)
    filled_at: datetime | None = None


@dataclass
class Position:
    """Current holding of a stock."""

    stock_code: str
    quantity: int
    avg_cost: float
    current_price: float = 0.0
    buy_date: date | None = None
    industry: str = ""  # for the industry-concentration risk cap

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def pnl(self) -> float:
        return (self.current_price - self.avg_cost) * self.quantity

    @property
    def pnl_pct(self) -> float:
        if self.avg_cost == 0:
            return 0.0
        return (self.current_price - self.avg_cost) / self.avg_cost


@dataclass
class Portfolio:
    """Portfolio state."""

    cash: float
    positions: dict[str, Position] = field(default_factory=dict)

    @property
    def market_value(self) -> float:
        return sum(p.market_value for p in self.positions.values())

    @property
    def total_value(self) -> float:
        return self.cash + self.market_value
